### ISSUE TITLE
Fail to deploy due to missing rds DBClusterParameterGroup

### ISSUE THREAD

**Issue by DanyC97** [aws-samples/serverless-refarch-for-proxysql#24]
After the code was refactored for projen support it no longer gets deployed.

The issue is around the `ParameterGroup`

```
constructor(scope: cdk.Construct, id: string, props: DBProps ) {
    super(scope, id);
    // Aurora
    const dbcluster = new rds.DatabaseCluster(this, 'Database', {
      engine: props.engine ?? rds.DatabaseClusterEngine.AURORA,
      // masterUser: {
      //   username: props.masterUsername ?? DB_MASTER_USERNAME ?? 'admin',
      // },
      instanceProps: {
        instanceType: props.instanceType ?? new ec2.InstanceType('t3.small'),
        vpc: props.vpc,
      },
      parameterGroup: new rds.ParameterGroup(this, 'PG', {
        engine: props.engine ?? rds.DatabaseClusterEngine.AURORA,
        // engine: rds.DatabaseClusterEngine.AURORA_POSTGRESQL
        // engine: (props.engine === rds.DatabaseClusterEngine.AURORA_POSTGRESQL) ? 'aurora-postgresql11' : 'default.aurora5.6',
        // family: (props.engine === rds.DatabaseClusterEngine.AURORA_POSTGRESQL) ? 'aurora-postgresql11' : 'default.aurora5.6',
      }),
      removalPolicy: cdk.RemovalPolicy.DESTROY,
    });

```
which generate the CFN

```
............

  DBClusterPG63D835EE:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties:
      Description: Cluster parameter group for aurora5.6
      Family: aurora5.6
      Parameters: {}
    Metadata:
      aws:cdk:path: serverless-proxysql-stack/DBCluster/PG/Resource

.........
```
however this is not valid because the `Parameters` array can't be empty - see [cfn docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbclusterparametergroup.html#cfn-rds-dbclusterparametergroup-parameters)

If the below snippet is commented out

```
parameterGroup: new rds.ParameterGroup(this, 'PG', {
        engine: props.engine ?? rds.DatabaseClusterEngine.AURORA,
        // engine: rds.DatabaseClusterEngine.AURORA_POSTGRESQL
        // engine: (props.engine === rds.DatabaseClusterEngine.AURORA_POSTGRESQL) ? 'aurora-postgresql11' : 'default.aurora5.6',
        // family: (props.engine === rds.DatabaseClusterEngine.AURORA_POSTGRESQL) ? 'aurora-postgresql11' : 'default.aurora5.6',
      }),

```
the CFN won't create the resource and a default pg will be created.

Note - you can check the [docs](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/CHAP_Aurora.html) to see what Parameter key/ value can be changed

i.e 

`ParameterName=max_connections,ParameterValue=5000`
