### ISSUE TITLE
support secret parameter for ecs task definitinon with Fargate

### ISSUE THREAD

**Issue by pahud** [aws-samples/serverless-refarch-for-proxysql#7]
https://github.com/aws-samples/serverless-refarch-for-proxysql/blob/42cb45344c069e35b910d29f5cc4207fc9b88599/lib/index.ts#L160-L161

> It is only supported to inject the full contents of a secret as an environment variable. Specifying a specific JSON key or version is not supported at this time. 
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/specifying-sensitive-data-secrets.html

depends on https://github.com/aws/containers-roadmap/issues/385

**Comment by snese** [comment]
@pahud  The issue https://github.com/aws/containers-roadmap/issues/385 had closed, let's move on to next stage, lol

**Comment by DanyC97** [comment]
in case i haven't misunderstood the issue, i think the code is [present](https://github.com/aws-samples/serverless-refarch-for-proxysql/blob/master/lib/index.ts#L226-L229) as far as i can see and can confirm in the generated CFN templates that it does what is supposed to do

```yaml

ProxySQLTask66A1033A:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Environment:
            - Name: DB_WRITER_HOSTNAME
              Value: writer.proxysql.local
            - Name: DB_READER_HOSTNAME
              Value: reader.proxysql.local
            - Name: DB_WRITER_PORT
              Value: '3306'
            - Name: DB_READER_PORT
              Value: '3306'
            - Name: DB_MASTER_USERNAME
              Value: admin
          Essential: true
          Image: !Join
            - ''
            - - 12345.dkr.ecr.us-east-1.
              - !Ref 'AWS::URLSuffix'
              - /aws-cdk/assets:0a48c0d6e2f688ca9f4b45efafa4dc5b6955193dc045a30b5f73131013ed3a6a
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref 'ProxySQLTaskproxysqlLogGroup48D393F6'
              awslogs-stream-prefix: proxysql-main
              awslogs-region: us-east-1
          Name: proxysql
          PortMappings:
            - ContainerPort: 6033
              Protocol: tcp
            - ContainerPort: 6032
              Protocol: tcp
          Secrets:
            - Name: DB_MASTER_PASSWORD
              ValueFrom: !Ref 'ProxySQLAuroraMasterSecret65F602CE'
            - Name: RADMIN_PASSWORD
              ValueFrom: !Ref 'ProxySQLRAdminPassword14486454'

....

  ProxySQLAuroraMasterSecret65F602CE:
    Type: AWS::SecretsManager::Secret
    Properties:
      GenerateSecretString:
        ExcludePunctuation: true
        PasswordLength: 12
      Name: ProxysqlFargateStack-auroraMasterSecret
    Metadata:
      aws:cdk:path: ProxysqlFargateStack/ProxySQL/AuroraMasterSecret/Resource
  ProxySQLRAdminPassword14486454:
    Type: AWS::SecretsManager::Secret
    Properties:
      GenerateSecretString:
        ExcludePunctuation: true
        PasswordLength: 12
      Name: ProxysqlFargateStack-radmin_pwd
    Metadata:
      aws:cdk:path: ProxysqlFargateStack/ProxySQL/RAdminPassword/Resource

```
Hence i think it can be closed?

Edit

And if what i wrote above is correct then the readme can be udpated & [remove](https://github.com/aws-samples/serverless-refarch-for-proxysql#custom-master-password-secret) the stale section
